### ISSUE TITLE
请问一直报错该怎么解决

### ISSUE THREAD

**Issue by 1045925330** [GhostStar/Arknights-Armada#1]
192.168.1.13:44810: CONNECT ak-gs-gf.hypergryph.com:443
 << Cannot establish TLS with client (sni: ak-gs-gf.hypergryph.com): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')])")

已经安装了mitmdump的证书

**Comment by GhostStar** [comment]
请问您是使用的什么设备？安卓7.0以上版本应用默认不信任用户添加的证书：

- Root 后使用 Xposed + JustTrustMe
- 使用 VirtualXposed 等免 Root 框架+JustTrustMe
- 【推荐】使用模拟器或 iOS 设备

如果非以上问题，请确认用浏览器是否可以正常打开其他 https 网站，如果同样不能请确认证书是否正确添加并信任。

**Comment by 1045925330** [comment]
> 请问您是使用的什么设备？安卓7.0以上版本应用默认不信任用户添加的证书：
> 
> * Root 后使用 Xposed + JustTrustMe
> * 使用 VirtualXposed 等免 Root 框架+JustTrustMe
> * 【推荐】使用模拟器或 iOS 设备
> 
> 如果非以上问题，请确认用浏览器是否可以正常打开其他 https 网站，如果同样不能请确认证书是否正确添加并信任。

我是用的安卓11的手机+xposed+justrustme
浏览器可以打开https网站
![image](https://user-images.githubusercontent.com/30003970/107749419-866efb00-6d55-11eb-947b-f31e458eb80c.png)

**Comment by GhostStar** [comment]
请问其他应用 https 请求正常吗？看错误还是感觉应用没有信任证书，因为我这边没有安卓设备所以不太好复现。或者你可以尝试在前面套一层 fiddler 看看是否可以正常抓到请求。

另外可以在 mitmproxy 的 issues 下搜索相关问题看看是否对你有帮助。

**Comment by 1045925330** [comment]
> 请问其他应用 https 请求正常吗？看错误还是感觉应用没有信任证书，因为我这边没有安卓设备所以不太好复现。或者你可以尝试在前面套一层 fiddler 看看是否可以正常抓到请求。
> 
> 另外可以在 mitmproxy 的 issues 下搜索相关问题看看是否对你有帮助。

确实是证书的问题，我把用户证书转换为系统证书就好了，justtrustme这个模块似乎在安卓11上无法生效。
不过有个新问题，就是为什么我进入游戏后只有131个干员，似乎新干员全都没有，character_table.json已经是最新的了。

**Comment by GhostStar** [comment]
这个问题我没有遇到，可能因为我只有111个干员....理论上不应该不过我也没法确认这个问题
