### ISSUE TITLE
第六步失败

### ISSUE THREAD

**Issue by frozenblackflame** [GhostStar/Arknights-Armada#12]
按照操作一步步完成，但是就是第六步一直失败。界面没出现能天使，控制台没有输出干员信息。求解

**Comment by Tinhone** [comment]
虽然没搞过这个，但据我所知，YJ更新了反抓包（去年十一月左右），所以这个项目应该失效了

**Comment by frozenblackflame** [comment]
> 虽然没搞过这个，但据我所知，YJ更新了反抓包（去年十一月左右），所以这个项目应该失效了

谢谢

**Comment by WERT760873A** [comment]
听过可以通过改HOST可以进行抓包 而且这个项目很久没更新了模组之类的都没有 肯定是需要更新的 可惜更新反抓包之后大佬们都不更新了

**Comment by Oniisancon** [comment]
想請教一下，第三步要怎麼做

**Comment by Oniisancon** [comment]
無論怎樣自己都想試一試

**Comment by frozenblackflame** [comment]
> 听过可以通过改HOST可以进行抓包 而且这个项目很久没更新了模组之类的都没有 肯定是需要更新的 可惜更新反抓包之后大佬们都不更新了

好的，了解了。不知道你知不知道有没有最新可用的方舟修改器吗？

**Comment by frozenblackflame** [comment]
> 想請教一下，第三步要怎麼做

就点一下超链，然后下载文件放到python文件同级目录下就好了。不过按照楼上的大佬所说，这个项目应该是过时了。所以不推荐耗费时间。

**Comment by Oniisancon** [comment]
> > 想請教一下，第三步要怎麼做
> 
> 就点一下超链，然后下载文件放到python文件同级目录下就好了。不过按照楼上的大佬所说，这个项目应该是过时了。所以不推荐耗费时间。

怎麼把下載文件放到Python文件同級目錄啊，現在純粹好奇

**Comment by frozenblackflame** [comment]
建议谷歌

**Comment by frozenblackflame** [comment]
> 

建议谷歌

**Comment by Oniisancon** [comment]
> 建议谷歌

我當然是找過才來問呀，看不明白
