### ISSUE TITLE
TLS报握手错误

### ISSUE THREAD

**Issue by Resbonsiblyat** [GhostStar/Arknights-Armada#2]
无论抓取什么类型的HTTPS请求，都提示Cannot establish TLS with client(sni: 请求的链接 ): TlsException("SSL handshake error :   SysCallError(-1, 'Unexpected EOF')")
请问大佬如何解决= =感谢！

**Comment by GhostStar** [comment]
请将证书添加至设备系统信任，安卓7.0以上版本应用默认不信任用户添加的证书：

- Root 后使用 Xposed + JustTrustMe
- 使用 VirtualXposed 等免 Root 框架+JustTrustMe
- 【推荐】使用模拟器或 iOS 设备

**Comment by Resbonsiblyat** [comment]
我ios设备没添加针对根证书启用完全信任 = = 哈哈哈哈哈哈 傻了
目前能看到已拥有的干员全部拉满，但不能战斗或者解锁干员故事等，报这个错
![image](https://user-images.githubusercontent.com/32755370/107871235-b267b900-6eda-11eb-8bec-b2215575267a.png)
游戏内报与神经网络链接丢失，请重新链接 错误号400
再次求教大佬= =多谢！新年快乐！

**Comment by Resbonsiblyat** [comment]
![image](https://user-images.githubusercontent.com/32755370/107871354-9b759680-6edb-11eb-99f5-5f395cad6af5.png)
截图不清楚 重新截一个

**Comment by GhostStar** [comment]
这个工具的原理是欺骗本地客户端，所以只能进行常规战斗以及龙门，不支持危机合约和其他和干员数据相关的操作。可以先在编队页面进行好编队再进战斗试试。

**Comment by Resbonsiblyat** [comment]
了解了！谢谢！我尝试了龙门，没有问题 主线第六章以后不可以用

**Comment by GhostStar** [comment]
请问具体是6-几？我现在进度刚好也在第六章，没有注意到这个问题

**Comment by Resbonsiblyat** [comment]
啊，今天尝试发现可以了，那可能是其他的原因导致的？我现在似乎不能复现。当时的情况是，我先看了下代码的部分，看到有battleStart字段的解析，然后想试一下活动的副本能不能被解析到，发现活动的战斗似乎能解析到但不知道为什么不能欺骗服务器，可能战斗在服务器上模拟？然后触发400错误重连，此时打主线第六章再一次触发400错误，重连后尝试龙门，正常工作。今天再试主线发现没有问题。。。可能是我的环境问题。

**Comment by GhostStar** [comment]
活动图我测试也是可以的，不支持的只有合约，通常可能是编队数据和服务器不一致导致，可以重开游戏换个编队试试
