### ISSUE TITLE
請問該如何自訂義探員?

### ISSUE THREAD

**Issue by chiajen870907** [GhostStar/Arknights-Armada#3]
請問大大該如何自訂義探員?

**Comment by GhostStar** [comment]
在脚本中 customChar 里面添加，干员序号为启动时获取到的干员列表对应获取干员的顺序，干员名称为 [character_table.json](https://github.com/Kengxxiao/ArknightsGameData/blob/master/zh_CN/gamedata/excel/character_table.json) 内的 characterPrefabKey。

注意只能修改已有的干员为其他的角色，如修改第五个干员为年，第六个干员为夕，具体格式参考下面代码：

```json
customChar = {
    "5": "char_2014_nian",
    "6": "char_2015_dusk"
}
```

**Comment by chiajen870907** [comment]
![image](https://user-images.githubusercontent.com/50796514/109165672-c6eb6180-77b6-11eb-960e-4fc01b7ac9ac.png)

我想將22號修改為能天使
我輸入
customChar = {
     "22": "char_103_angel"
}
但是重啟遊戲後 並無任何變化耶?

**Comment by chiajen870907** [comment]
![image](https://user-images.githubusercontent.com/50796514/109166346-93f59d80-77b7-11eb-943a-68b4bbd51074.png)

請問我想將19號更改為星熊
customChar = {
     "19": "char_136_hsguma"
}
但是這樣進遊戲並無任何變化耶?

**Comment by GhostStar** [comment]
之前代码没有同步到主线，现在已经更新，请下载最新代码再试一次。

**Comment by chiajen870907** [comment]
感謝角色替換成功了，但是想請問一下
為什麼有些替換出來的角色不能編隊？
編隊後會提示網路錯誤！

**Comment by GhostStar** [comment]
不要使用3星以下角色进行替换，替换完成后先进行编队再进行游戏。
